---
- name: Run preflight check
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Run preflight-check.sh from bootstrap-utils
      ansible.builtin.script:
        cmd: ../../bootstrap-utils/preflight-check.sh
      register: preflight_output

    - name: Show preflight-check output
      ansible.builtin.debug:
        msg: "{{ preflight_output.stdout_lines }}"
