---
- import_playbook: credentials/create-vars-files.yml
- import_playbook: credentials/secret-preflight-checks.yml
- import_playbook: credentials/register-rancher-suse-repos.yml
- import_playbook: credentials/create-suse-appco-pull-secret.yml
- import_playbook: credentials/create-nvidia-ngc-pull-secret.yml
